#!/bin/bash

realpath() {
  OURPWD=$PWD
  cd "$(dirname "$1")"
  LINK=$(readlink "$(basename "$1")")
  while [ "$LINK" ]; do
    cd "$(dirname "$LINK")"
    LINK=$(readlink "$(basename "$1")")
  done
  REALPATH="$PWD/$(basename "$1")"
  cd "$OURPWD"
  echo "$REALPATH"
}

root="$( realpath $(dirname "${BASH_SOURCE[0]}") )"

cd "$root/../toolchains/nRF5"

patch -d nrf5SDKforMeshv500src -p1 < "$root/sdk/nrf5SDKforMeshv500src.patch"

echo "Done!"
