#!/bin/bash

realpath() {
  OURPWD=$PWD
  cd "$(dirname "$1")"
  LINK=$(readlink "$(basename "$1")")
  while [ "$LINK" ]; do
    cd "$(dirname "$LINK")"
    LINK=$(readlink "$(basename "$1")")
  done
  REALPATH="$PWD/$(basename "$1")"
  cd "$OURPWD"
  echo "$REALPATH"
}

root="$( realpath $(dirname "${BASH_SOURCE[0]}") )"
. "$root/versions.sh"

cd "$root/../toolchains/nRF5"

mesh_dir="nrf5SDKforMeshv${NRF5_MESH_SDK_VERSION}src"
mesh_patch="$root/sdk/${mesh_dir}.patch"
if [[ -s "$mesh_patch" ]]; then
  patch -d "$mesh_dir" -p1 < "$mesh_patch"
fi

# Also patch the main SDK's Makefile.common if a patch is present
sdk_version="$NRF5_SDK_VERSION"
sdk_patch="$root/sdk/${sdk_version}.patch"
if [[ -n "${sdk_version:-}" && -s "$sdk_patch" ]]; then
  echo "Applying main SDK patch: $sdk_patch"
  # Patch uses git-style a/ b/ paths; apply relative to SDK root
  patch -d "$sdk_version" -p1 < "$sdk_patch"
fi

echo "Done!"
