#!/bin/bash

realpath() {
  OURPWD=$PWD
  cd "$(dirname "$1")"
  LINK=$(readlink "$(basename "$1")")
  while [ "$LINK" ]; do
    cd "$(dirname "$LINK")"
    LINK=$(readlink "$(basename "$1")")
  done
  REALPATH="$PWD/$(basename "$1")"
  cd "$OURPWD"
  echo "$REALPATH"
}

root="$( realpath $(dirname "${BASH_SOURCE[0]}") )"

cd "$root"

perl -0pi -e "s/(diff|\-\-\-|\+\+\+|\@\@)(.*?)$(printf '\r')/\1\2/g" sdk/nrf5SDKforMeshv500src.patch

echo "Done!"
