#!/bin/bash

realpath() {
  OURPWD=$PWD
  cd "$(dirname "$1")"
  LINK=$(readlink "$(basename "$1")")
  while [ "$LINK" ]; do
    cd "$(dirname "$LINK")"
    LINK=$(readlink "$(basename "$1")")
  done
  REALPATH="$PWD/$(basename "$1")"
  cd "$OURPWD"
  echo "$REALPATH"
}

root="$( realpath $(dirname "${BASH_SOURCE[0]}") )"

cd "$root"

. "$root/versions.sh"
mesh_dir="nrf5SDKforMeshv${NRF5_MESH_SDK_VERSION}src"
perl -0pi -e "s/(diff|\-\-\-|\+\+\+|\@\@)(.*?)$(printf '\r')/\1\2/g" "sdk/${mesh_dir}.patch"

sdk_version="$NRF5_SDK_VERSION"
if [[ -n "${sdk_version:-}" ]]; then
  perl -0pi -e "s/(diff|\-\-\-|\+\+\+|\@\@)(.*?)$(printf '\r')/\1\2/g" "sdk/${sdk_version}.patch"
fi

echo "Done!"
