#!/bin/bash

realpath() {
  OURPWD=$PWD
  cd "$(dirname "$1")"
  LINK=$(readlink "$(basename "$1")")
  while [ "$LINK" ]; do
    cd "$(dirname "$LINK")"
    LINK=$(readlink "$(basename "$1")")
  done
  REALPATH="$PWD/$(basename "$1")"
  cd "$OURPWD"
  echo "$REALPATH"
}

root="$( realpath $(dirname "${BASH_SOURCE[0]}") )"
. "$root/versions.sh"

cd "$root/../toolchains/nRF5"

mesh_dir="nrf5SDKforMeshv${NRF5_MESH_SDK_VERSION}src"
if [[ -d "$mesh_dir" ]]; then
  find "$mesh_dir" '(' \
      -name \*-baseline -o \
      -name \*-merge -o \
      -name \*-original -o \
      -name \*.orig -o \
      -name \*.rej \
  ')' -delete
fi

sdk_version="$NRF5_SDK_VERSION"
if [[ -n "${sdk_version:-}" && -d "$sdk_version" ]]; then
  find "$sdk_version" '(' \
      -name \*-baseline -o \
      -name \*-merge -o \
      -name \*-original -o \
      -name \*.orig -o \
      -name \*.rej \
  ')' -delete
fi

echo "Done!"
